server:
  port: 8099
  servlet:
    context-path: /api

spring:
  main:
    allow-circular-references: true
  application:
    name: authentication-service
  datasource:
    url: jdbc:mysql://localhost:3306/dbuser?useSSL=false&serverTimezone=UTC
    username: root
    password: bintangmada
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
