spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/dborder?useSSL=false&serverTimezone=UTC
    username: root
    password: bintangmada
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083
  servlet:
    context-path: /api
